---
This is metadata:

Kernel: bio_python312 (Python 3.12.13)
Path:   /var/home/aeersriv/.anaconda3/envs/bio_python312/bin/python
---

# Ligand Preparation (Stage 0.1.4)

Prepare the ligand for molecular docking.

## Preliminaries

In [ ]:
from os.path import abspath

import meeko
import molscrub
import pandas as pd
from rdkit import Chem

from src.utils.prep import ligand_prep

In [2]:
CWD: str = abspath(".")
DATA: str = f"{CWD}/../data"

## Data

In [3]:
native = pd.read_csv(
        f"{DATA}/natural_antibiotics.csv", index_col=0
    )
mirror = pd.read_csv(f"{DATA}/mirror_ligand.csv", index_col=0)

In [4]:
native.head()

,Amoxicillin,Piperacillin,Ticarcillin,Cefepime,Cefazolin,Ceftolozane,Ceftriaxone,Ceftazidime,Aztreonam,Imipenem,...,Fosfomycin,Amikacin,Tobramycin,Streptomycin,Kanamycin,Trimethoprim,Sulfamethoxazole,Ciprofloxacin,Levofloxacin,Moxifloxacin
cid,33613,43672,36921,5479537,33255,53234134,5479530,5481173,5742832,104838,...,446987,37768,36294,19649,6032,5578,5329,2764,149096,152946
smiles,CC1([C@@H](N2[C@H](S1)[C@@H](C2=O)NC(=O)[C@@H]...,CCN1CCN(C(=O)C1=O)C(=O)N[C@H](C2=CC=CC=C2)C(=O...,CC1([C@@H](N2[C@H](S1)[C@@H](C2=O)NC(=O)[C@@H]...,C[N+]1(CCCC1)CC2=C(N3[C@@H]([C@@H](C3=O)NC(=O)...,CC1=NN=C(S1)SCC2=C(N3[C@@H]([C@@H](C3=O)NC(=O)...,CC(C)(C(=O)O)O/N=C(/C1=NSC(=N1)N)\C(=O)N[C@H]2...,CN1C(=NC(=O)C(=O)N1)SCC2=C(N3[C@@H]([C@@H](C3=...,CC(C)(C(=O)O)O/N=C(/C1=CSC(=N1)N)\C(=O)N[C@H]2...,C[C@H]1[C@@H](C(=O)N1S(=O)(=O)O)NC(=O)/C(=N\OC...,C[C@H]([C@@H]1[C@H]2CC(=C(N2C1=O)C(=O)O)SCCN=CN)O,...,C[C@H]1[C@H](O1)P(=O)(O)O,C1[C@@H]([C@H]([C@@H]([C@H]([C@@H]1NC(=O)[C@H]...,C1[C@@H]([C@H]([C@@H]([C@H]([C@@H]1N)O[C@@H]2[...,C[C@H]1[C@@]([C@H]([C@@H](O1)O[C@@H]2[C@H]([C@...,C1[C@H]([C@@H]([C@H]([C@@H]([C@H]1N)O[C@@H]2[C...,COC1=CC(=CC(=C1OC)OC)CC2=CN=C(N=C2N)N,CC1=CC(=NO1)NS(=O)(=O)C2=CC=C(C=C2)N,C1CC1N2C=C(C(=O)C3=CC(=C(C=C32)N4CCNCC4)F)C(=O)O,C[C@H]1COC2=C3N1C=C(C(=O)C3=CC(=C2N4CCN(CC4)C)...,COC1=C2C(=CC(=C1N3C[C@@H]4CCCN[C@@H]4C3)F)C(=O...
inchi,InChI=1S/C16H19N3O5S/c1-16(2)11(15(23)24)19-13...,InChI=1S/C23H27N5O7S/c1-4-26-10-11-27(19(32)18...,InChI=1S/C15H16N2O6S2/c1-15(2)9(14(22)23)17-11...,InChI=1S/C19H24N6O5S2/c1-25(5-3-4-6-25)7-10-8-...,InChI=1S/C14H14N8O4S3/c1-6-17-18-14(29-6)28-4-...,"InChI=1S/C23H30N12O8S2/c1-23(2,20(40)41)43-31-...",InChI=1S/C18H18N8O7S3/c1-25-18(22-12(28)13(29)...,"InChI=1S/C22H22N6O7S2/c1-22(2,20(33)34)35-26-1...","InChI=1S/C13H17N5O8S2/c1-5-7(10(20)18(5)28(23,...",InChI=1S/C12H17N3O4S/c1-6(16)9-7-4-8(20-3-2-14...,...,"InChI=1S/C3H7O4P/c1-2-3(7-2)8(4,5)6/h2-3H,1H3,...",InChI=1S/C22H43N5O13/c23-2-1-8(29)20(36)27-7-3...,InChI=1S/C18H37N5O9/c19-3-9-8(25)2-7(22)17(29-...,"InChI=1S/C21H39N7O12/c1-5-21(36,4-30)16(40-17-...",InChI=1S/C18H36N4O11/c19-2-6-10(25)12(27)13(28...,InChI=1S/C14H18N4O3/c1-19-10-5-8(6-11(20-2)12(...,InChI=1S/C10H11N3O3S/c1-7-6-10(12-16-7)13-17(1...,InChI=1S/C17H18FN3O3/c18-13-7-11-14(8-15(13)20...,InChI=1S/C18H20FN3O4/c1-10-9-26-17-14-11(16(23...,InChI=1S/C21H24FN3O4/c1-29-20-17-13(19(26)14(2...

In [5]:
mirror.head()

,Amoxicillin,Piperacillin,Ticarcillin,Cefepime,Cefazolin,Ceftolozane,Ceftriaxone,Ceftazidime,Aztreonam,Imipenem,...,Fosfomycin,Amikacin,Tobramycin,Streptomycin,Kanamycin,Trimethoprim,Sulfamethoxazole,Ciprofloxacin,Levofloxacin,Moxifloxacin
cid,33613,43672,36921,5479537,33255,53234134,5479530,5481173,5742832,104838,...,446987,37768,36294,19649,6032,5578,5329,2764,149096,152946
smiles,CC1([C@@H](N2[C@H](S1)[C@@H](C2=O)NC(=O)[C@@H]...,CCN1CCN(C(=O)C1=O)C(=O)N[C@H](C2=CC=CC=C2)C(=O...,CC1([C@@H](N2[C@H](S1)[C@@H](C2=O)NC(=O)[C@@H]...,C[N+]1(CCCC1)CC2=C(N3[C@@H]([C@@H](C3=O)NC(=O)...,CC1=NN=C(S1)SCC2=C(N3[C@@H]([C@@H](C3=O)NC(=O)...,CC(C)(C(=O)O)O/N=C(/C1=NSC(=N1)N)\C(=O)N[C@H]2...,CN1C(=NC(=O)C(=O)N1)SCC2=C(N3[C@@H]([C@@H](C3=...,CC(C)(C(=O)O)O/N=C(/C1=CSC(=N1)N)\C(=O)N[C@H]2...,C[C@H]1[C@@H](C(=O)N1S(=O)(=O)O)NC(=O)/C(=N\OC...,C[C@H]([C@@H]1[C@H]2CC(=C(N2C1=O)C(=O)O)SCCN=CN)O,...,C[C@H]1[C@H](O1)P(=O)(O)O,C1[C@@H]([C@H]([C@@H]([C@H]([C@@H]1NC(=O)[C@H]...,C1[C@@H]([C@H]([C@@H]([C@H]([C@@H]1N)O[C@@H]2[...,C[C@H]1[C@@]([C@H]([C@@H](O1)O[C@@H]2[C@H]([C@...,C1[C@H]([C@@H]([C@H]([C@@H]([C@H]1N)O[C@@H]2[C...,COC1=CC(=CC(=C1OC)OC)CC2=CN=C(N=C2N)N,CC1=CC(=NO1)NS(=O)(=O)C2=CC=C(C=C2)N,C1CC1N2C=C(C(=O)C3=CC(=C(C=C32)N4CCNCC4)F)C(=O)O,C[C@H]1COC2=C3N1C=C(C(=O)C3=CC(=C2N4CCN(CC4)C)...,COC1=C2C(=CC(=C1N3C[C@@H]4CCCN[C@@H]4C3)F)C(=O...
inchi,InChI=1S/C16H19N3O5S/c1-16(2)11(15(23)24)19-13...,InChI=1S/C23H27N5O7S/c1-4-26-10-11-27(19(32)18...,InChI=1S/C15H16N2O6S2/c1-15(2)9(14(22)23)17-11...,InChI=1S/C19H24N6O5S2/c1-25(5-3-4-6-25)7-10-8-...,InChI=1S/C14H14N8O4S3/c1-6-17-18-14(29-6)28-4-...,"InChI=1S/C23H30N12O8S2/c1-23(2,20(40)41)43-31-...",InChI=1S/C18H18N8O7S3/c1-25-18(22-12(28)13(29)...,"InChI=1S/C22H22N6O7S2/c1-22(2,20(33)34)35-26-1...","InChI=1S/C13H17N5O8S2/c1-5-7(10(20)18(5)28(23,...",InChI=1S/C12H17N3O4S/c1-6(16)9-7-4-8(20-3-2-14...,...,"InChI=1S/C3H7O4P/c1-2-3(7-2)8(4,5)6/h2-3H,1H3,...",InChI=1S/C22H43N5O13/c23-2-1-8(29)20(36)27-7-3...,InChI=1S/C18H37N5O9/c19-3-9-8(25)2-7(22)17(29-...,"InChI=1S/C21H39N7O12/c1-5-21(36,4-30)16(40-17-...",InChI=1S/C18H36N4O11/c19-2-6-10(25)12(27)13(28...,InChI=1S/C14H18N4O3/c1-19-10-5-8(6-11(20-2)12(...,InChI=1S/C10H11N3O3S/c1-7-6-10(12-16-7)13-17(1...,InChI=1S/C17H18FN3O3/c18-13-7-11-14(8-15(13)20...,InChI=1S/C18H20FN3O4/c1-10-9-26-17-14-11(16(23...,InChI=1S/C21H24FN3O4/c1-29-20-17-13(19(26)14(2...
mirror_smi,CC1(C)S[C@H]2[C@@H](NC(=O)[C@@H](N)c3ccc(O)cc3...,CCN1CCN(C(=O)N[C@H](C(=O)N[C@H]2C(=O)N3[C@H]2S...,CC1(C)S[C@H]2[C@@H](NC(=O)[C@@H](C(=O)O)c3ccsc...,CO/N=C(\C(=O)N[C@H]1C(=O)N2C(C(=O)[O-])=C(C[N+...,Cc1nnc(SCC2=C(C(=O)O)N3C(=O)[C@H](NC(=O)Cn4cnn...,Cn1c(N)c(NC(=O)NCCN)c[n+]1CC1=C(C(=O)[O-])N2C(...,CO/N=C(\C(=O)N[C@H]1C(=O)N2C(C(=O)O)=C(CSc3nc(...,CC(C)(O/N=C(\C(=O)N[C@H]1C(=O)N2C(C(=O)[O-])=C...,C[C@@H]1[C@@H](NC(=O)/C(=N\OC(C)(C)C(=O)O)c2cs...,C[C@H](O)[C@@H]1C(=O)N2C(C(=O)O)=C(SCCN=CN)C[C...,...,C[C@H]1O[C@H]1P(=O)(O)O,NCC[C@@H](O)C(=O)N[C@H]1C[C@@H](N)[C@H](O[C@@H...,NC[C@@H]1O[C@@H](O[C@@H]2[C@@H](O)[C@H](O[C@@H...,CN[C@H]1[C@@H](O[C@@H]2[C@@H](O[C@@H]3[C@@H](O...,NC[C@@H]1O[C@@H](O[C@@H]2[C@@H](O)[C@H](O[C@@H...,COc1cc(Cc2cnc(N)nc2N)cc(OC)c1OC,Cc1cc(NS(=O)(=O)c2ccc(N)cc2)no1,O=C(O)c1cn(C2CC2)c2cc(N3CCNCC3)c(F)cc2c1=O,C[C@@H]1COc2c(N3CCN(C)CC3)c(F)cc3c(=O)c(C(=O)O...,COc1c(N2C[C@H]3CCCN[C@H]3C2)c(F)cc2c(=O)c(C(=O...

## Ligand Preparation

In [6]:
prepped_mir: list[str] = []
prepped_nat: list[str] = []

for nat, mir in zip(native, mirror):
    nat_prep: str | None = ligand_prep(
        native[nat]["smiles"],
        f"Native-{native[nat]['cid']}",
        f"{DATA}/ligand_prep"
    )
    mir_prep: str | None = ligand_prep(
        mirror[mir]["mirror_smi"],
        f"Mirror-{mirror[mir]['cid']}",
        f"{DATA}/ligand_prep"
    )

    if nat_prep:
        prepped_nat.append(nat_prep)

    if mir_prep:
        prepped_mir.append(mir_prep)

Scrubing Native-33613 with scrub.py CC1([C@@H](N2[C@H](S1)[C@@H](C2=O)NC(=O)[C@@H](C3=CC=C(C=C3)O)N)C(=O)O)C -o /var/home/aeersriv/Documents/FLD-1-antibiotics_mirror_life/antibiotics_mirror_life-CODE/notebooks/../data/ligand_prep/scrub/Native-33613-scrub.sdf --ph 7.4 --skip_tautomer
Scrub completed.
Summary of what happened:
Input molecules supplied: 1
mols processed: 1, skipped by rdkit: 0, failed: 0
nr isomers (tautomers and acid/base conjugates): 1 (avg. 1.000 per mol)
nr conformers:  1 (avg. 1.000 per isomer, 1.000 per mol)
Preparing Native-33613 with mk_prepare_ligand.py -i /var/home/aeersriv/Documents/FLD-1-antibiotics_mirror_life/antibiotics_mirror_life-CODE/notebooks/../data/ligand_prep/scrub/Native-33613-scrub.sdf -o /var/home/aeersriv/Documents/FLD-1-antibiotics_mirror_life/antibiotics_mirror_life-CODE/notebooks/../data/ligand_prep/Native-33613-prepped.pdbqt
Input molecules processed: 1, skipped: 0
PDBQT files written: 1
PDBQT files not written due to error: 0
Input molecules with errors: 0
Scrubing Mirror-33613 with scrub.py CC1(C)S[C@H]2[C@@H](NC(=O)[C@@H](N)c3ccc(O)cc3)C(=O)N2[C@@H]1C(=O)O -o /var/home/aeersriv/Documents/FLD-1-antibiotics_mirror_life/antibiotics_mirror_life-CODE/notebooks/../data/ligand_prep/scrub/Mirror-33613-scrub.sdf --ph 7.4 --skip_tautomer
Scrub completed.
Summary of what happened:
Input molecules supplied: 1
mols processed: 1, skipped by rdkit: 0, failed: 0
nr isomers (tautomers and acid/base conjugates): 1 (avg. 1.000 per mol)
nr conformers:  1 (avg. 1.000 per isomer, 1.000 per mol)
Preparing Mirror-33613 with mk_prepare_ligand.py -i /var/home/aeersriv/Documents/FLD-1-antibiotics_mirror_life/antibiotics_mirror_life-CODE/notebooks/../data/ligand_prep/scrub/Mirror-33613-scrub.sdf -o /var/home/aeersriv/Documents/FLD-1-antibiotics_mirror_life/antibiotics_mirror_life-CODE/notebooks/../data/ligand_prep/Mirror-33613-prepped.pdbqt
Input molecules processed: 1, skipped: 0
PDBQT files written: 1
PDBQT files not written due to error: 0
Input molecules with errors: 0
Scrubing Native-43672 with scrub.py CCN1CCN(C(=O)C1=O)C(=O)N[C@H](C2=CC=CC=C2)C(=O)N[C@H]3[C@@H]4N(C3=O)[C@H](C(S4)(C)C)C(=O)O -o /var/home/aeersriv/Documents/FLD-1-antibiotics_mirror_life/antibiotics_mirror_life-CODE/notebooks/../data/ligand_prep/scrub/Native-43672-scrub.sdf --ph 7.4 --skip_tautomer
Scrub completed.
Summary of what happened:
Input molecules supplied: 1
mols processed: 1, skipped by rdkit: 0, failed: 0
nr isomers (tautomers and acid/base conjugates): 1 (avg. 1.000 per mol)
nr conformers:  1 (avg. 1.000 per isomer, 1.000 per mol)
Preparing Native-43672 with mk_prepare_ligand.py -i /var/home/aeersriv/Documents/FLD-1-antibiotics_mirror_life/antibiotics_mirror_life-CODE/notebooks/../data/ligand_prep/scrub/Native-43672-scrub.sdf -o /var/home/aeersriv/Documents/FLD-1-antibiotics_mirror_life/antibiotics_mirror_life-CODE/notebooks/../data/ligand_prep/Native-43672-prepped.pdbqt
Input molecules processed: 1, skipped: 0
PDBQT files written: 1
PDBQT files not written due to error: 0
Input molecules with errors: 0
Scrubing Mirror-43672 with scrub.py CCN1CCN(C(=O)N[C@H](C(=O)N[C@H]2C(=O)N3[C@H]2SC(C)(C)[C@H]3C(=O)O)c2ccccc2)C(=O)C1=O -o /var/home/aeersriv/Documents/FLD-1-antibiotics_mirror_life/antibiotics_mirror_life-CODE/notebooks/../data/ligand_prep/scrub/Mirror-43672-scrub.sdf --ph 7.4 --skip_tautomer
Scrub completed.
Summary of what happened:
Input molecules supplied: 1
mols processed: 1, skipped by rdkit: 0, failed: 0
nr isomers (tautomers and acid/base conjugates): 1 (avg. 1.000 per mol)
nr conformers:  1 (avg. 1.000 per isomer, 1.000 per mol)
Preparing Mirror-43672 with mk_prepare_ligand.py -i /var/home/aeersriv/Documents/FLD-1-antibiotics_mirror_life/antibiotics_mirror_life-CODE/notebooks/../data/ligand_prep/scrub/Mirror-43672-scrub.sdf -o /var/home/aeersriv/Documents/FLD-1-antibiotics_mirror_life/antibiotics_mirror_life-CODE/notebooks/../data/ligand_prep/Mirror-43672-prepped.pdbqt
Input molecules processed: 1, skipped: 0
PDBQT files written: 1
PDBQT files not written due to error: 0
Input molecules with errors: 0
Scrubing Native-36921 with scrub.py CC1([C@@H](N2[C@H](S1)[C@@H](C2=O)NC(=O)[C@@H](C3=CSC=C3)C(=O)O)C(=O)O)C -o /var/home/aeersriv/Documents/FLD-1-antibiotics_mirror_life/antibiotics_mirror_life-CODE/notebooks/../data/ligand_prep/scrub/Native-36921-scrub.sdf --ph 7.4 --skip_tautomer
Scrub completed.
Summary of what happened:
Input molecules supplied: 1
mols processed: 1, skipped by rdkit: 0, failed: 0
nr isomers (tautomers and acid/base conjugates): 1 (avg. 1.000 per mol)
nr conformers:  1 (avg. 1.000 per isomer, 1.000 per mol)
Preparing Native-36921 with mk_prepare_ligand.py -i /var/home/aeersriv/Documents/FLD-1-antibiotics_mirror_life/antibiotics_mirror_life-CODE/notebooks/../data/ligand_prep/scrub/Native-36921-scrub.sdf -o /var/home/aeersriv/Documents/FLD-1-antibiotics_mirror_life/antibiotics_mirror_life-CODE/notebooks/../data/ligand_prep/Native-36921-prepped.pdbqt
Input molecules processed: 1, skipped: 0
PDBQT files written: 1
PDBQT files not written due to error: 0
Input molecules with errors: 0
Scrubing Mirror-36921 with scrub.py CC1(C)S[C@H]2[C@@H](NC(=O)[C@@H](C(=O)O)c3ccsc3)C(=O)N2[C@@H]1C(=O)O -o /var/home/aeersriv/Documents/FLD-1-antibiotics_mirror_life/antibiotics_mirror_life-CODE/notebooks/../data/ligand_prep/scrub/Mirror-36921-scrub.sdf --ph 7.4 --skip_tautomer
Scrub completed.
Summary of what happened:
Input molecules supplied: 1
mols processed: 1, skipped by rdkit: 0, failed: 0
nr isomers (tautomers and acid/base conjugates): 1 (avg. 1.000 per mol)
nr conformers:  1 (avg. 1.000 per isomer, 1.000 per mol)
Preparing Mirror-36921 with mk_prepare_ligand.py -i /var/home/aeersriv/Documents/FLD-1-antibiotics_mirror_life/antibiotics_mirror_life-CODE/notebooks/../data/ligand_prep/scrub/Mirror-36921-scrub.sdf -o /var/home/aeersriv/Documents/FLD-1-antibiotics_mirror_life/antibiotics_mirror_life-CODE/notebooks/../data/ligand_prep/Mirror-36921-prepped.pdbqt
Input molecules processed: 1, skipped: 0
PDBQT files written: 1
PDBQT files not written due to error: 0
Input molecules with errors: 0
Scrubing Native-5479537 with scrub.py C[N+]1(CCCC1)CC2=C(N3[C@@H]([C@@H](C3=O)NC(=O)/C(=N\OC)/C4=CSC(=N4)N)SC2)C(=O)[O-] -o /var/home/aeersriv/Documents/FLD-1-antibiotics_mirror_life/antibiotics_mirror_life-CODE/notebooks/../data/ligand_prep/scrub/Native-5479537-scrub.sdf --ph 7.4 --skip_tautomer
Scrub completed.
Summary of what happened:
Input molecules supplied: 1
mols processed: 1, skipped by rdkit: 0, failed: 0
nr isomers (tautomers and acid/base conjugates): 1 (avg. 1.000 per mol)
nr conformers:  1 (avg. 1.000 per isomer, 1.000 per mol)
Preparing Native-5479537 with mk_prepare_ligand.py -i /var/home/aeersriv/Documents/FLD-1-antibiotics_mirror_life/antibiotics_mirror_life-CODE/notebooks/../data/ligand_prep/scrub/Native-5479537-scrub.sdf -o /var/home/aeersriv/Documents/FLD-1-antibiotics_mirror_life/antibiotics_mirror_life-CODE/notebooks/../data/ligand_prep/Native-5479537-prepped.pdbqt
Input molecules processed: 1, skipped: 0
PDBQT files written: 1
PDBQT files not written due to error: 0
Input molecules with errors: 0
Scrubing Mirror-5479537 with scrub.py CO/N=C(\C(=O)N[C@H]1C(=O)N2C(C(=O)[O-])=C(C[N+]3(C)CCCC3)CS[C@@H]12)c1csc(N)n1 -o /var/home/aeersriv/Documents/FLD-1-antibiotics_mirror_life/antibiotics_mirror_life-CODE/notebooks/../data/ligand_prep/scrub/Mirror-5479537-scrub.sdf --ph 7.4 --skip_tautomer
Scrub completed.
Summary of what happened:
Input molecules supplied: 1
mols processed: 1, skipped by rdkit: 0, failed: 0
nr isomers (tautomers and acid/base conjugates): 1 (avg. 1.000 per mol)
nr conformers:  1 (avg. 1.000 per isomer, 1.000 per mol)
Preparing Mirror-5479537 with mk_prepare_ligand.py -i /var/home/aeersriv/Documents/FLD-1-antibiotics_mirror_life/antibiotics_mirror_life-CODE/notebooks/../data/ligand_prep/scrub/Mirror-5479537-scrub.sdf -o /var/home/aeersriv/Documents/FLD-1-antibiotics_mirror_life/antibiotics_mirror_life-CODE/notebooks/../data/ligand_prep/Mirror-5479537-prepped.pdbqt
Input molecules processed: 1, skipped: 0
PDBQT files written: 1
PDBQT files not written due to error: 0
Input molecules with errors: 0
Scrubing Native-33255 with scrub.py CC1=NN=C(S1)SCC2=C(N3[C@@H]([C@@H](C3=O)NC(=O)CN4C=NN=N4)SC2)C(=O)O -o /var/home/aeersriv/Documents/FLD-1-antibiotics_mirror_life/antibiotics_mirror_life-CODE/notebooks/../data/ligand_prep/scrub/Native-33255-scrub.sdf --ph 7.4 --skip_tautomer
Scrub completed.
Summary of what happened:
Input molecules supplied: 1
mols processed: 1, skipped by rdkit: 0, failed: 0
nr isomers (tautomers and acid/base conjugates): 1 (avg. 1.000 per mol)
nr conformers:  1 (avg. 1.000 per isomer, 1.000 per mol)
Preparing Native-33255 with mk_prepare_ligand.py -i /var/home/aeersriv/Documents/FLD-1-antibiotics_mirror_life/antibiotics_mirror_life-CODE/notebooks/../data/ligand_prep/scrub/Native-33255-scrub.sdf -o /var/home/aeersriv/Documents/FLD-1-antibiotics_mirror_life/antibiotics_mirror_life-CODE/notebooks/../data/ligand_prep/Native-33255-prepped.pdbqt
Input molecules processed: 1, skipped: 0
PDBQT files written: 1
PDBQT files not written due to error: 0
Input molecules with errors: 0
Scrubing Mirror-33255 with scrub.py Cc1nnc(SCC2=C(C(=O)O)N3C(=O)[C@H](NC(=O)Cn4cnnn4)[C@@H]3SC2)s1 -o /var/home/aeersriv/Documents/FLD-1-antibiotics_mirror_life/antibiotics_mirror_life-CODE/notebooks/../data/ligand_prep/scrub/Mirror-33255-scrub.sdf --ph 7.4 --skip_tautomer
Scrub completed.
Summary of what happened:
Input molecules supplied: 1
mols processed: 1, skipped by rdkit: 0, failed: 0
nr isomers (tautomers and acid/base conjugates): 1 (avg. 1.000 per mol)
nr conformers:  1 (avg. 1.000 per isomer, 1.000 per mol)
Preparing Mirror-33255 with mk_prepare_ligand.py -i /var/home/aeersriv/Documents/FLD-1-antibiotics_mirror_life/antibiotics_mirror_life-CODE/notebooks/../data/ligand_prep/scrub/Mirror-33255-scrub.sdf -o /var/home/aeersriv/Documents/FLD-1-antibiotics_mirror_life/antibiotics_mirror_life-CODE/notebooks/../data/ligand_prep/Mirror-33255-prepped.pdbqt
Input molecules processed: 1, skipped: 0
PDBQT files written: 1
PDBQT files not written due to error: 0
Input molecules with errors: 0
Scrubing Native-53234134 with scrub.py CC(C)(C(=O)O)O/N=C(/C1=NSC(=N1)N)\C(=O)N[C@H]2[C@@H]3N(C2=O)C(=C(CS3)C[N+]4=CC(=C(N4C)N)NC(=O)NCCN)C(=O)[O-] -o /var/home/aeersriv/Documents/FLD-1-antibiotics_mirror_life/antibiotics_mirror_life-CODE/notebooks/../data/ligand_prep/scrub/Native-53234134-scrub.sdf --ph 7.4 --skip_tautomer
Scrub completed.
Summary of what happened:
Input molecules supplied: 1
mols processed: 1, skipped by rdkit: 0, failed: 0
nr isomers (tautomers and acid/base conjugates): 1 (avg. 1.000 per mol)
nr conformers:  1 (avg. 1.000 per isomer, 1.000 per mol)
Preparing Native-53234134 with mk_prepare_ligand.py -i /var/home/aeersriv/Documents/FLD-1-antibiotics_mirror_life/antibiotics_mirror_life-CODE/notebooks/../data/ligand_prep/scrub/Native-53234134-scrub.sdf -o /var/home/aeersriv/Documents/FLD-1-antibiotics_mirror_life/antibiotics_mirror_life-CODE/notebooks/../data/ligand_prep/Native-53234134-prepped.pdbqt
Input molecules processed: 1, skipped: 0
PDBQT files written: 1
PDBQT files not written due to error: 0
Input molecules with errors: 0
Scrubing Mirror-53234134 with scrub.py Cn1c(N)c(NC(=O)NCCN)c[n+]1CC1=C(C(=O)[O-])N2C(=O)[C@H](NC(=O)/C(=N\OC(C)(C)C(=O)O)c3nsc(N)n3)[C@@H]2SC1 -o /var/home/aeersriv/Documents/FLD-1-antibiotics_mirror_life/antibiotics_mirror_life-CODE/notebooks/../data/ligand_prep/scrub/Mirror-53234134-scrub.sdf --ph 7.4 --skip_tautomer
Scrub completed.
Summary of what happened:
Input molecules supplied: 1
mols processed: 1, skipped by rdkit: 0, failed: 0
nr isomers (tautomers and acid/base conjugates): 1 (avg. 1.000 per mol)
nr conformers:  1 (avg. 1.000 per isomer, 1.000 per mol)
Preparing Mirror-53234134 with mk_prepare_ligand.py -i /var/home/aeersriv/Documents/FLD-1-antibiotics_mirror_life/antibiotics_mirror_life-CODE/notebooks/../data/ligand_prep/scrub/Mirror-53234134-scrub.sdf -o /var/home/aeersriv/Documents/FLD-1-antibiotics_mirror_life/antibiotics_mirror_life-CODE/notebooks/../data/ligand_prep/Mirror-53234134-prepped.pdbqt
Input molecules processed: 1, skipped: 0
PDBQT files written: 1
PDBQT files not written due to error: 0
Input molecules with errors: 0
Scrubing Native-5479530 with scrub.py CN1C(=NC(=O)C(=O)N1)SCC2=C(N3[C@@H]([C@@H](C3=O)NC(=O)/C(=N\OC)/C4=CSC(=N4)N)SC2)C(=O)O -o /var/home/aeersriv/Documents/FLD-1-antibiotics_mirror_life/antibiotics_mirror_life-CODE/notebooks/../data/ligand_prep/scrub/Native-5479530-scrub.sdf --ph 7.4 --skip_tautomer
Scrub completed.
Summary of what happened:
Input molecules supplied: 1
mols processed: 1, skipped by rdkit: 0, failed: 0
nr isomers (tautomers and acid/base conjugates): 1 (avg. 1.000 per mol)
nr conformers:  1 (avg. 1.000 per isomer, 1.000 per mol)
Preparing Native-5479530 with mk_prepare_ligand.py -i /var/home/aeersriv/Documents/FLD-1-antibiotics_mirror_life/antibiotics_mirror_life-CODE/notebooks/../data/ligand_prep/scrub/Native-5479530-scrub.sdf -o /var/home/aeersriv/Documents/FLD-1-antibiotics_mirror_life/antibiotics_mirror_life-CODE/notebooks/../data/ligand_prep/Native-5479530-prepped.pdbqt
Input molecules processed: 1, skipped: 0
PDBQT files written: 1
PDBQT files not written due to error: 0
Input molecules with errors: 0
Scrubing Mirror-5479530 with scrub.py CO/N=C(\C(=O)N[C@H]1C(=O)N2C(C(=O)O)=C(CSc3nc(=O)c(=O)[nH]n3C)CS[C@@H]12)c1csc(N)n1 -o /var/home/aeersriv/Documents/FLD-1-antibiotics_mirror_life/antibiotics_mirror_life-CODE/notebooks/../data/ligand_prep/scrub/Mirror-5479530-scrub.sdf --ph 7.4 --skip_tautomer
Scrub completed.
Summary of what happened:
Input molecules supplied: 1
mols processed: 1, skipped by rdkit: 0, failed: 0
nr isomers (tautomers and acid/base conjugates): 1 (avg. 1.000 per mol)
nr conformers:  1 (avg. 1.000 per isomer, 1.000 per mol)
Preparing Mirror-5479530 with mk_prepare_ligand.py -i /var/home/aeersriv/Documents/FLD-1-antibiotics_mirror_life/antibiotics_mirror_life-CODE/notebooks/../data/ligand_prep/scrub/Mirror-5479530-scrub.sdf -o /var/home/aeersriv/Documents/FLD-1-antibiotics_mirror_life/antibiotics_mirror_life-CODE/notebooks/../data/ligand_prep/Mirror-5479530-prepped.pdbqt
Input molecules processed: 1, skipped: 0
PDBQT files written: 1
PDBQT files not written due to error: 0
Input molecules with errors: 0
Scrubing Native-5481173 with scrub.py CC(C)(C(=O)O)O/N=C(/C1=CSC(=N1)N)\C(=O)N[C@H]2[C@@H]3N(C2=O)C(=C(CS3)C[N+]4=CC=CC=C4)C(=O)[O-] -o /var/home/aeersriv/Documents/FLD-1-antibiotics_mirror_life/antibiotics_mirror_life-CODE/notebooks/../data/ligand_prep/scrub/Native-5481173-scrub.sdf --ph 7.4 --skip_tautomer
Scrub completed.
Summary of what happened:
Input molecules supplied: 1
mols processed: 1, skipped by rdkit: 0, failed: 0
nr isomers (tautomers and acid/base conjugates): 1 (avg. 1.000 per mol)
nr conformers:  1 (avg. 1.000 per isomer, 1.000 per mol)
Preparing Native-5481173 with mk_prepare_ligand.py -i /var/home/aeersriv/Documents/FLD-1-antibiotics_mirror_life/antibiotics_mirror_life-CODE/notebooks/../data/ligand_prep/scrub/Native-5481173-scrub.sdf -o /var/home/aeersriv/Documents/FLD-1-antibiotics_mirror_life/antibiotics_mirror_life-CODE/notebooks/../data/ligand_prep/Native-5481173-prepped.pdbqt
Input molecules processed: 1, skipped: 0
PDBQT files written: 1
PDBQT files not written due to error: 0
Input molecules with errors: 0
Scrubing Mirror-5481173 with scrub.py CC(C)(O/N=C(\C(=O)N[C@H]1C(=O)N2C(C(=O)[O-])=C(C[n+]3ccccc3)CS[C@@H]12)c1csc(N)n1)C(=O)O -o /var/home/aeersriv/Documents/FLD-1-antibiotics_mirror_life/antibiotics_mirror_life-CODE/notebooks/../data/ligand_prep/scrub/Mirror-5481173-scrub.sdf --ph 7.4 --skip_tautomer
Scrub completed.
Summary of what happened:
Input molecules supplied: 1
mols processed: 1, skipped by rdkit: 0, failed: 0
nr isomers (tautomers and acid/base conjugates): 1 (avg. 1.000 per mol)
nr conformers:  1 (avg. 1.000 per isomer, 1.000 per mol)
Preparing Mirror-5481173 with mk_prepare_ligand.py -i /var/home/aeersriv/Documents/FLD-1-antibiotics_mirror_life/antibiotics_mirror_life-CODE/notebooks/../data/ligand_prep/scrub/Mirror-5481173-scrub.sdf -o /var/home/aeersriv/Documents/FLD-1-antibiotics_mirror_life/antibiotics_mirror_life-CODE/notebooks/../data/ligand_prep/Mirror-5481173-prepped.pdbqt
Input molecules processed: 1, skipped: 0
PDBQT files written: 1
PDBQT files not written due to error: 0
Input molecules with errors: 0
Scrubing Native-5742832 with scrub.py C[C@H]1[C@@H](C(=O)N1S(=O)(=O)O)NC(=O)/C(=N\OC(C)(C)C(=O)O)/C2=CSC(=N2)N -o /var/home/aeersriv/Documents/FLD-1-antibiotics_mirror_life/antibiotics_mirror_life-CODE/notebooks/../data/ligand_prep/scrub/Native-5742832-scrub.sdf --ph 7.4 --skip_tautomer
Scrub completed.
Summary of what happened:
Input molecules supplied: 1
mols processed: 1, skipped by rdkit: 0, failed: 0
nr isomers (tautomers and acid/base conjugates): 1 (avg. 1.000 per mol)
nr conformers:  1 (avg. 1.000 per isomer, 1.000 per mol)
Preparing Native-5742832 with mk_prepare_ligand.py -i /var/home/aeersriv/Documents/FLD-1-antibiotics_mirror_life/antibiotics_mirror_life-CODE/notebooks/../data/ligand_prep/scrub/Native-5742832-scrub.sdf -o /var/home/aeersriv/Documents/FLD-1-antibiotics_mirror_life/antibiotics_mirror_life-CODE/notebooks/../data/ligand_prep/Native-5742832-prepped.pdbqt
Input molecules processed: 1, skipped: 0
PDBQT files written: 1
PDBQT files not written due to error: 0
Input molecules with errors: 0
Scrubing Mirror-5742832 with scrub.py C[C@@H]1[C@@H](NC(=O)/C(=N\OC(C)(C)C(=O)O)c2csc(N)n2)C(=O)N1S(=O)(=O)O -o /var/home/aeersriv/Documents/FLD-1-antibiotics_mirror_life/antibiotics_mirror_life-CODE/notebooks/../data/ligand_prep/scrub/Mirror-5742832-scrub.sdf --ph 7.4 --skip_tautomer
Scrub completed.
Summary of what happened:
Input molecules supplied: 1
mols processed: 1, skipped by rdkit: 0, failed: 0
nr isomers (tautomers and acid/base conjugates): 1 (avg. 1.000 per mol)
nr conformers:  1 (avg. 1.000 per isomer, 1.000 per mol)
Preparing Mirror-5742832 with mk_prepare_ligand.py -i /var/home/aeersriv/Documents/FLD-1-antibiotics_mirror_life/antibiotics_mirror_life-CODE/notebooks/../data/ligand_prep/scrub/Mirror-5742832-scrub.sdf -o /var/home/aeersriv/Documents/FLD-1-antibiotics_mirror_life/antibiotics_mirror_life-CODE/notebooks/../data/ligand_prep/Mirror-5742832-prepped.pdbqt
Input molecules processed: 1, skipped: 0
PDBQT files written: 1
PDBQT files not written due to error: 0
Input molecules with errors: 0
Scrubing Native-104838 with scrub.py C[C@H]([C@@H]1[C@H]2CC(=C(N2C1=O)C(=O)O)SCCN=CN)O -o /var/home/aeersriv/Documents/FLD-1-antibiotics_mirror_life/antibiotics_mirror_life-CODE/notebooks/../data/ligand_prep/scrub/Native-104838-scrub.sdf --ph 7.4 --skip_tautomer
Scrub completed.
Summary of what happened:
Input molecules supplied: 1
mols processed: 1, skipped by rdkit: 0, failed: 0
nr isomers (tautomers and acid/base conjugates): 1 (avg. 1.000 per mol)
nr conformers:  1 (avg. 1.000 per isomer, 1.000 per mol)
Preparing Native-104838 with mk_prepare_ligand.py -i /var/home/aeersriv/Documents/FLD-1-antibiotics_mirror_life/antibiotics_mirror_life-CODE/notebooks/../data/ligand_prep/scrub/Native-104838-scrub.sdf -o /var/home/aeersriv/Documents/FLD-1-antibiotics_mirror_life/antibiotics_mirror_life-CODE/notebooks/../data/ligand_prep/Native-104838-prepped.pdbqt
Input molecules processed: 1, skipped: 0
PDBQT files written: 1
PDBQT files not written due to error: 0
Input molecules with errors: 0
Scrubing Mirror-104838 with scrub.py C[C@H](O)[C@@H]1C(=O)N2C(C(=O)O)=C(SCCN=CN)C[C@@H]12 -o /var/home/aeersriv/Documents/FLD-1-antibiotics_mirror_life/antibiotics_mirror_life-CODE/notebooks/../data/ligand_prep/scrub/Mirror-104838-scrub.sdf --ph 7.4 --skip_tautomer
Scrub completed.
Summary of what happened:
Input molecules supplied: 1
mols processed: 1, skipped by rdkit: 0, failed: 0

In [7]:
print(
    f"Prepared native ligands: {len(prepped_nat)}\n"
    f"Prepared mirror ligands: {len(prepped_mir)}\n"
)

Prepared native ligands: 34
Prepared mirror ligands: 34